services:
  ad-finals-baxcalibur:
    build:
      context: .
    container_name: ad-finals-baxcalibur-service
    ports:
      - "8002:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-finals-baxcalibur-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminBaxcalibur
      MONGO_INITDB_ROOT_PASSWORD: passwordBaxcalibur
      MONGO_INITDB_DATABASE: baxcaliburDb
    ports:
      - "27112:27017"
    volumes:
      - ad-finals-baxcalibur-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: ad-finals-baxcalibur-postgresql
    restart: always
    environment:
      POSTGRES_USER: adminBaxcalibur
      POSTGRES_PASSWORD: passwordBaxcalibur
      POSTGRES_DB: baxcaliburDb
    ports:
      - "5114:5432"
    volumes:
      - ad-finals-baxcalibur-postgresql:/data/db/postgresql

volumes:
  ad-finals-baxcalibur-mongodb:
    driver: local
  ad-finals-baxcalibur-postgresql:
    driver: local
